In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('load.csv')

In [3]:
df

,Unnamed: 0,funded_amnt_inv,term,int_rate,installment,emp_length,home_ownership,annual_inc,verification_status,purpose,total_pymnt,total_rec_prncp,total_rec_int,last_pymnt_amnt,repay_fail
0,0,0,36,0.00,0.00,0,RENT,0,0,major_purchase,0.000000,0.00,0.00,0.00,1
1,1,2500,36,13.98,85.42,4,RENT,20004,0,other,3075.291779,2500.00,575.29,90.85,0
2,2,5000,36,15.95,175.67,4,RENT,59000,0,debt_consolidation,2948.760000,1909.02,873.81,175.67,1
3,3,7000,36,9.91,225.58,10,MORTGAGE,53796,0,other,8082.391880,7000.00,1082.39,1550.27,0
4,4,2000,36,5.42,60.32,10,RENT,30000,0,debt_consolidation,2161.663244,2000.00,161.66,53.12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37480,38475,3000,36,11.99,99.63,3,RENT,74250,1,credit_card,3586.619764,3000.00,586.62,100.30,0
37481,38476,10400,36,13.49,352.88,9,RENT,62000,1,credit_card,12703.534030,10400.00,2303.53,393.08,0
37482,38477,10531,60,14.96,250.77,10,MORTGAGE,95088,1,debt_consolidation,14202.267530,10550.00,3652.27,5439.96,0
37483,38478,10000,36,16.89,355.99,1,RENT,48720,0,debt_consolidation,12815.178320,10000.00,2815.18,380.63,0
37484,38479,3200,36,13.49,108.58,7,RENT,38400,1,debt_consolidation,3908.767275,3200.00,708.77,111.88,0

In [18]:
import autokeras
from autokeras import StructuredDataClassifier
from sklearn.model_selection import train_test_split

In [19]:
search=StructuredDataClassifier(max_trials=15)

In [20]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['repay_fail']),
                                                 df['repay_fail'],
                                                 test_size=0.2,
                                                random_state=42)

In [21]:
search.fit(x=X_train,y=y_train,verbose=1)

C:\Users\nabee\anaconda3\Lib\site-packages\autokeras\adapters\input_adapters.py:73: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if isinstance(dataset, np.ndarray) and dataset.dtype == np.object:

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations